---

- name: 'Install dependece packages'
  apt:
    name:
        - mysql-server-5.6
        - python-mysqldb
    state: latest
  become: yes
- name: 'Create MySQL database'
  mysql_db:
    name: "{{ wp_db_name }}"
    login_user: root
    state: present
- name: 'Create MySQL user'
  mysql_user:
    login_user: root
    name: "{{ wp_username }}"
    password: "{{ wp_user_password }}"
    priv: "{{ wp_db_name }}.*:ALL"
    state: present
    host: "{{ item }}"
  loop:
    - "{{ wp_host_ip }}"
- name: 'Configure MySQL to allow remote connections'
  copy:
    src: 'files/my.cnf'
    dest: '/etc/mysql/my.cnf'
  become: yes
  notify:
    - restart mysql